# Generated by Django 4.1.3 on 2022-11-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apisan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='stu',
        ),
        migrations.AlterModelTable(
            name='stu',
            table='stu',
        ),
    ]
