# Generated by Django 4.1.3 on 2022-11-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apisan', '0002_remove_student_passby_remove_student_roll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singer',
            old_name='city',
            new_name='gender',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Singer',
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='apisan.singer')),
            ],
        ),
    ]
